name: Django CI

on:
  push:
    branches: [ test_yaml ]
  pull_request:
    branches: [ test_yaml ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        cd backend 
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test