name: Frontend CI test

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-python@v2
      with:
        node-version: 14.x
    - name: Run Tests
      run: |
        cd frontend 
        npm test